jobs:
- name: staging
  serial: true
  plan:
  - { get: staging, trigger: true }
  - task: execute
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: bodymindarts/cepler
          tag: latest
      inputs:
      - name: staging
        path: repo
      outputs:
      - name: repo
      run:
        dir: repo
        path: ls
        args:
          - "-al"
  - put: staging
    params:
      repository: repo

- name: testflight
  serial: true
  plan:
  - { get: testflight, trigger: true }
  - task: execute
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: bodymindarts/cepler
          tag: latest
      inputs:
      - name: testflight
        path: repo
      outputs:
      - name: repo
      run:
        dir: repo
        path: ls
        args:
          - "-al"
  - put: testflight
    params:
      repository: repo

resources:
- name: staging
  type: cepler
  source:
    uri: git@github.com:bodymindarts/cepler-test
    branch: main
    private_key: ((github.private_key))
    environment: staging

- name: testflight
  type: cepler
  source:
    uri: git@github.com:bodymindarts/cepler-test
    branch: main
    private_key: ((github.private_key))
    environment: testflight

resource_types:
- name: cepler
  type: registry-image
  source:
    repository: bodymindarts/cepler
    tag: latest

