jobs:
- name: staging
  serial: true
  plan:
  - { get: staging, trigger: true }

- name: testflight
  serial: true
  plan:
  - { get: testflight, trigger: true }

resources:
- name: staging
  type: cepler
  source:
    uri: git@github.com:bodymindarts/cepler-test
    branch: main
    private_key: ((github.private_key))
    environment: staging

- name: testflight
  type: cepler
  source:
    uri: git@github.com:bodymindarts/cepler-test
    branch: main
    private_key: ((github.private_key))
    environment: testflight

resource_types:
- name: cepler
  type: registry-image
  source:
    repository: bodymindarts/cepler
    tag: latest

